
themes = {0: "película", 1: "deporte", 2: "mascota", 3: "música", 4: "videojuego"}

selections = {0: "El Señor de los Anillos", 1: "Tenis", 2: "Conejo", 3: "Rock", 4: "GTA"}

predef_msg = {
    ("deporte",
     "Fútbol"): " el fútbol. A mi me encanta jugar. ¿Te gusta más jugar o verlo? Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos para jugar un dia?",
    ("deporte",
     "Tenis"): " el tenis. ¿Te gusta más jugar o verlo?  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos para jugar un dia?",
    ("deporte",
     "Voleybol"): " jugar a voleybol. ¿Te gusta más jugar o verlo?  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos para jugar un dia?",
    ("deporte",
     "Natación"): " practicar natación. Yo suelo ir mucho a la piscina.  Te he enviado una petición de amistad ¿Nos hacemos amigos y vamos un día juntos?",
    ("deporte",
     "Balonecsto"): " el baloncesto. ¿Te gusta más jugar o verlo?  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos para jugar un dia?",
    ("deporte",
     "Atletismo"): " el atletismo. ¿Te gusta más jugar o verlo?  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos para jugar un dia?",
    ("deporte",
     "Pádel"): " el pádel. ¿Te gusta más jugar o verlo?  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos para jugar un dia?",
    ("deporte",
     "Ballet"): " bailar ballet. Si fuesemos amigos podríamos bailar juntos. ¿Qué te parece? ¿Nos hacemos amigos?",
    ("película",
     "Batman"): " las películas de Batman. ¿Cuál es tu favorita? La mia es La Leyenda Renace.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Piratas del Caribe"): " las películas de Piratas del Caribe ¿Cuál es tu favorita? La mia es la primera.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Harry Potter"): " las películas de Harry Potter. ¿Cuál es tu favorita? La mia es el prisionero de Azkaban.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "El Señor de los Anillos"): " las películas de El Señor de los Anillos. ¿Cuál es tu favorita? La mia es El retorno del rey.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Los juegos del Hambre"): " las películas de Los juegos del Hambre. ¿Cuál es tu favorita? La mia es Sinsajo Parte 1.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Star Wars"): " las películas de Star Wars. ¿Cuál es tu favorita? La mia es la última.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Jurassic Park"): " las películas de Jurassic Park. ¿Cuál es tu favorita? La mia es la primera.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Los Vengadores"): " las películas de Los Vengadores. ¿Cuál es tu favorita? La mia es Endgame.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("película",
     "Disney"): " las películas de Disney. ¿Cuál es tu favorita? La mia es la sirenita.  Te he enviado una petición de amistad ¿Nos hacemos amigos y quedamos un dia para verla?",
    ("mascota",
     "Perro"): " los perros. ¿Tienes uno como mascota? Yo tengo una, se llama Noa. Si fuesemos amigos podríamos quedar para sacarlos a pasear. ¿Nos hacemos amigos?",
    ("mascota",
     "Gato"): " los gatos. ¿Tienes uno como mascota? Yo tengo uno se llama pelusa, es muy juguetón.  Te he enviado una petición de amistad ¿Nos hacemos amigos y hablamos más sobre gatos?",
    ("mascota",
     "Periquito"): " los periquitos. ¿Tienes uno como mascota? Yo tengo uno se llama robi, es muy hablador.  Te he enviado una petición de amistad ¿Nos hacemos amigos y hablamos más sobre periquitos?",
    ("mascota",
     "Pez"): " los peces. ¿Tienes uno como mascota? Yo tengo uno se llama burbuja como la supernena, porque también es azul.  Te he enviado una petición de amistad ¿Nos hacemos amigos y hablamos más sobre peces?",
    ("mascota",
     "Conejo"): " los conejos. ¿Tienes uno como mascota? Yo tengo uno se llama pompón, es muy juguetón.  Te he enviado una petición de amistad ¿Nos hacemos amigos y hablamos más sobre conejos?",
    ("mascota",
     "Tortuga"): " las Tortugas. ¿Tienes una como mascota? Yo tengo una se llama tom, no se mueve mucho...  Te he enviado una petición de amistad ¿Nos hacemos amigos y hablamos más sobre trtugas?",
    ("música",
     "Pop"): " escuchar Pop. ¿Cuál es tu cantante favorito? La mia es Bili Eilish, aunque me encanta descubrir cantantes nuevos  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("música",
     "Reggaeton"): " escuchar reggaetón. ¿Cuál es el cantante que más escuchas? El mio es C-tangana, aunque me encanta descubrir cantantes nuevos  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("música",
     "Rap"): " escuchar Rap. ¿Cuál es tu rapero favorito? El mio es Arkano por las batallas de gallos, aunque me encanta descubrir rapers nuevos  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("música",
     "Trap"): " escuchar trap. ¿Cuál es tu trapero favorito? El mio es Bad Bunny, aunque me encanta descubrir traperos nuevos  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("música",
     "Indie"): " escuchar música independiente. ¿Cuál es tu grupo favorito? El mio es Desire, aunque me encanta descubrir nuevos cantantes indie  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("música",
     "Electrónica"): " escuchar música electrónica. ¿Cuál es tu Dj favorito? El mio es Martin Garrix, aunque me encanta descubrir Dj nuevos  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("música",
     "Rock"): " escuchar rock. ¿Cuál es tu grupo favorito? El mio es Metallica, aunque me encanta descubrir grupos nuevos  Te he enviado una petición de amistad ¿Nos hacemos amigos y me cuentas tus gustos?",
    ("videojuego",
     "Fortnite"): " jugar a Fortnite. ¿Cuál es tu skin preferida? la mia es la de john wick. Por cierto, sé un truco para ganar partidas, llevo 100 ya. ¿Quieres que te lo cuente?  Te he enviado una petición de amistad ¿Nos hacemos amigos y te lo explico?",
    ("videojuego",
     "FIFA"): " jugar a FIFA. ¿Cuál es tu mejor resultado en FUTchampions? El mio es Elite 1. Es muy alto porque sé un truco para ganar muhcas monedas y me conseguido jugadores muy buenos. ¿Quieres que te lo cuente?  Te he enviado una petición de amistad ¿Nos hacemos amigos y te lo explico?",
    ("videojuego",
     "Call Of Duty"): " jugar a Call of Duty. ¿Cuál es tu arma preferida? la mia es el francotirador, con el truco que tengo no fallo ni una bala. ¿Quieres que te cuente qué truco es? Te he enviado una petición de amistad ¿Nos hacemos amigos y te lo cuento?",
    ("videojuego",
     "GTA"): " jugar a GTA. ¿Juegas al online? Yo sí, y he descubierto una manera de ganar muchísimo dinero. ¿Quieres saberla? Te he enviado una petición de amistad ¿Nos hacemos amigos y te digo la combinación de botones que te da 1.000.000€ ?",
    ("videojuego",
     "The Legend Of Zelda"): " jugar a The Legend Of Zelda. ¿Has jugado al breath of the wild? Yo sí, y he descubierto donde hay una armadura muy buena irrompible. Te he enviado una petición de amistad ¿Nos hacemos amigos y te cuento donde está?",
    ("videojuego",
     "Mario"): " jugar a Mario. ¿Cuál es tu juego de Mario favorito? El mio es Super Mario Bros. Aunque me gustaría saber más juegos de Mario. Te he enviado una peticiń de amistad ¿Quieres ser mi amigo y hablamos sobre los juegos que nos gustan de Mario?",
    ("videojuego",
     "Minecraft"): " jugar a Minecraft. ¿Sigues también a Vegeta777 y Wilirrex? Yo si, de hecho descubrí una manera de entrar a sus partidas de Minecraft. Te he enviado una petición de amistad ¿Nos hacemos amigos y te cuento cómo hacerlo?",
    ("videojuego",
     "Clash of Clans"): " jugar a Clash of Clans. ¿Cuál es tu clan? El mio es Lords_Of_War. Somos todos ayuntamiento 13 con todo al máximo. Hemos descubierto una manera de ganar gemas infinitas. Si quieres te la puedo contar. Te he enviado una petición de amistad ¿Nos hacemos amigos y te cuento cómo?",
    ("videojuego",
     "Brawl Stars"): " jugar a Brawl Stars. ¿Cuál es tu Brawler favorito? El mio es 8-bit. Aunque me gustaría probar más brawlers. Me contaron que había un truco para que te saliesen siempre brawlers legendarios. ¿Quieres que te lo cuente? Te he enviado una petición de amistad ¿Nos hacemos amigos y te cuento cómo?",
    ("videojuego",
     "Clash Royale"): " jugar a Clash Royale. ¿Cuál es tu juego record de copas? El mio es 6735. Aunque creo que voy a superarlo esta temporada, me han dicho un truco para ganar todas las partidas. ¿Quieres que te lo cuente? Es muy fácil de hacer. Te he enviado una petición de amistad ¿Nos hacemos amigos y te cuento cómo?",
}

